image: node:18 # Use a recent Node.js LTS version

cache:
  paths:
    - node_modules/

pages: # This job is automatically recognized by GitLab Pages
  stage: deploy
  script:
    - npm install -g @angular/cli@latest
    - npm install
    - ng build --configuration production --base-href /common-utils-ui/ # Assumes project name is common-utils-ui
    - echo "Verifying build output..."
    - |
      if [ ! -f "dist/common-utils-ui/index.html" ]; then
        echo "ERROR: index.html not found in dist/common-utils-ui/"
        ls -la dist/common-utils-ui/ # List contents for debugging
        exit 1
      fi
    - echo "Build output verified. Preparing public directory..."
    - rm -rf public
    - mkdir public
    - echo "Copying build artifacts from dist/common-utils-ui/ to public/"
    - cp -r dist/common-utils-ui/* public/
    - echo "Verifying public directory contents..."
    - |
      if [ ! -f "public/index.html" ]; then
        echo "ERROR: index.html not found in public/ after copy!"
        ls -la public/ # List contents for debugging
        exit 1
      fi
    - echo "Successfully copied artifacts to public directory."
  artifacts:
    paths:
      - public # GitLab Pages will serve files from this directory
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Deploy only when commits are made to the default branch (e.g., main or master)
